// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eunodppgwevommdfftzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bm9kcHBnd2V2b21tZGZmdHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDI5NDIsImV4cCI6MjA2NTI3ODk0Mn0.Iibp0HY0DgOdtIfYtqqndhtDsOuBhMevza29yxhPT6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);